### ISSUE TITLE
Similar work

### ISSUE THREAD

**Issue by vvzen** [yasuyuky/vscode-foxdot#4]
Hi @yasuyuky !

I just realized that we're doing the exact same thing in almost the exact same time span!
I recently started building a vscode extension for FoxDot here: https://github.com/vvzen/vscode-foxdot . I'm in a veeeeeery early stage and I never used the vscode extension API.
But it's fun and I got a barebone prototype working.

I was thinking that maybe instead of duplicating the efforts it's worth that I start contributing here?

I've seen that you've already implemented a bunch of features that I haven't yet tackled.

I was also curious of why you're using 
```
    foxdot.pythonPath
        Path of Python
```

instead of letting the user free to pick the right python environment where he has installed FoxDot. I feel more advanced users might like to have a dynamic way to using whatever python path they choose, instead of hard coding it.

Great to see some movement around this!
✌️

Valerio

**Comment by yasuyuky** [comment]
Hi Valerio!

Thank you for kindly informing me about your project.
I'm great to know your project too 🤣 

> I was thinking that maybe instead of duplicating the efforts it's worth that I start contributing here?

I'm glad to hear that. Your contribution is always welcome :+1:
There are a few things I want you to know for our collaboration:

1. It's a very early stage project too.
So I want to stay in control of the project for a while.

2. I can't commit to this project full time.
Currently, this is a hobby project, not my job.

3. I'm not a native English speaker.
I'm not confident in completely communicating my design intent.
But I promise always to treat you and other contributors with respect.


> I feel more advanced users might like to have a dynamic way to using whatever python path they choose, instead of hard coding it.

`foxdot.pythonPath` is an optional configuration and users can choose a dynamic way or override with this configuration. 
Of course, It's nice to clarify it's optional.
Thank you for pointing it out!
I'll improve the description soon.
